#!/bin/bash

# In order to include JavaNativeFoundation headers this is based on 
# https://macosx-port-dev.openjdk.java.narkive.com/QZT8BXTT/is-javanativefoundation-still-supported-on-os-x-10-10
# see also
# https://github.com/apple/openjdk/
SDK_ROOT="$(xcrun --show-sdk-path)"

gcc -Inative -arch x86_64 -o libAppleScriptEngine.dylib -dynamiclib -F${SDK_ROOT}/System/Library/Frameworks/JavaVM.framework/Frameworks -framework JavaVM -framework JavaNativeFoundation -framework Foundation -framework Carbon -framework Cocoa native/*.m 